import { chromium } from 'playwright';
import fs from 'fs';
import path from 'path';
import process from 'process';

// YouTube Video ID를 여기서 변경하세요
const YOUTUBE_VIDEO_ID = 'guRkQDSfiKk';

// 번역 방식 선택: 'youtube' (YouTube 자동번역) 또는 'papago' (Papago API 번역)
const TRANSLATION_METHOD: 'youtube' | 'papago' = 'youtube';

// YouTube URL 생성
const YOUTUBE_URL = `https://www.youtube.com/watch?v=${YOUTUBE_VIDEO_ID}`;

// 출력 디렉토리 설정
const OUTPUT_DIR = path.join(process.cwd(), 'dist-youtube-subtitles');
const VTT_DIR = path.join(process.cwd(), '..', '..', '..', 'datas', 'english', 'vtt');
const SCRIPTS_DIR = path.join(process.cwd(), '..', '..', '..', 'datas', 'english', 'scripts');
const ITEMS_JSON_PATH = path.join(process.cwd(), '..', '..', '..', 'datas', 'english', 'items.json');
const DICTIONARY_DIR = path.join(process.cwd(), '..', '..', '..', 'datas', 'english', 'dictionary');
const AUTO_TRANSLATION_DIR = path.join(process.cwd(), '..', '..', '..', 'datas', 'english', 'auto-translation');

interface SubtitleData {
  language: string;
  content: string;
  isAutoGenerated: boolean;
  url: string;
  originalJson?: any; // 원본 JSON 데이터 저장
}

interface SubtitleEntry {
  t: string;  // time in seconds like "0s", "6s"
  e: string;  // english text
  k: string;  // korean text
}

interface VideoItem {
  name: string;
  type: string;
  img: string;
  link: string;
}

interface PapagoResponse {
  items: Array<{
    entry: string;
    subEntry?: string;
    matchType: string;
    hanjaEntry?: string;
    phoneticSigns: Array<{
      type: string;
      sign: string;
    }>;
    pos: Array<{
      type: string;
      meanings: Array<{
        meaning: string;
        examples: Array<{
          text: string;
          translatedText: string;
        }>;
        originalMeaning: string;
      }>;
    }>;
    source: string;
    url: string;
    mUrl: string;
    expDicTypeForm: string;
    locale: string;
    conjugationList?: Array<{
      type: string;
      value: string;
    }>;
    aliasConjugation?: string;
    aliasConjugationPos?: string;
    gdid: string;
    expEntrySuperscript?: string;
  }>;
  examples: Array<{
    source: string;
    matchType: string;
    translatedText: string;
    text: string;
  }>;
  isWordType: boolean;
}

function convertJson3ToVtt(jsonData: any): string {
  try {
    if (!jsonData.events || !Array.isArray(jsonData.events)) {
      return '';
    }

    let vttContent = 'WEBVTT\n\n';
    let cueCount = 0;
    
    for (const event of jsonData.events) {
      if (event.segs && Array.isArray(event.segs)) {
        const startTime = formatTime(event.tStartMs || 0);
        const duration = event.dDurationMs || 3000;
        const endTime = formatTime((event.tStartMs || 0) + duration);
        
        const text = event.segs.map((seg: any) => seg.utf8 || '').join('').trim();
        
        if (text) {
          vttContent += `${startTime} --> ${endTime}\n${text}\n\n`;
          cueCount++;
        }
      }
    }
    
    console.log(`✅ Converted ${cueCount} subtitle cues to VTT format`);
    return vttContent;
  } catch (error) {
    console.log('❌ Error converting JSON3 to VTT:', error);
    return '';
  }
}

function formatTime(milliseconds: number): string {
  const totalSeconds = Math.floor(milliseconds / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  const ms = milliseconds % 1000;
  
  return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}.${ms.toString().padStart(3, '0')}`;
}

function parseVttTime(timeStr: string): number {
  const parts = timeStr.split(':');
  const hours = parseInt(parts[0]);
  const minutes = parseInt(parts[1]);
  const secondsParts = parts[2].split('.');
  const seconds = parseInt(secondsParts[0]);
  const milliseconds = parseInt(secondsParts[1]);
  
  return hours * 3600000 + minutes * 60000 + seconds * 1000 + milliseconds;
}

async function fetchDictionary(word: string): Promise<PapagoResponse | null> {
  try {
    const response = await fetch(`https://papago.naver.com/apis/dictionary/search?source=en&target=ko&text=${encodeURIComponent(word)}&locale=ko`, {
      headers: {
        "accept": "application/json",
        "accept-language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
        "authorization": "PPG ffbaf550-ce4b-4478-ae20-ee54a0e3cd60:0q77fVjSF1Qh3crEdIDMKQ==",
        "cache-control": "no-cache",
        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
        "pragma": "no-cache",
        "priority": "u=1, i",
        "sec-ch-ua": "\"Not_A Brand\";v=\"99\", \"Chromium\";v=\"142\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        'timestamp': Date.now().toString(),
        "x-apigw-partnerid": "papago",
        "x-ppg-ctype": "WEB_PC",
        "cookie": "NNB=ZFCDE4DECVCWQ; _ga_8P4PY65YZ2=GS2.1.s1749365250$o1$g0$t1749365250$j60$l0$h0; ba.uuid=4c6155ad-568d-4b70-bfac-a51e7da4bbcf; ASID=3b0589f40000019827bcdb750000001d; bnb_tooltip_shown_finance_v1=true; _ga=GA1.2.1705893687.1749365250; ab.storage.userId.7d7bb94a-f465-48e5-bec1-35db97daf128=g%3AZ2JG%7Ce%3Aundefined%7Cc%3A1761905082349%7Cl%3A1761905082350; ab.storage.deviceId.7d7bb94a-f465-48e5-bec1-35db97daf128=g%3A63dd0bf6-7986-8282-897c-5526a566b2ab%7Ce%3Aundefined%7Cc%3A1761905082350%7Cl%3A1761905082350; ab.storage.sessionId.7d7bb94a-f465-48e5-bec1-35db97daf128=g%3Ad2c680c5-2d3f-9d2b-c3fb-42785b70ed6b%7Ce%3A1761907197910%7Cc%3A1761905082349%7Cl%3A1761905397910; NV_WETR_LOCATION_RGN_M=\"MDYxNDAxMDE=\"; NV_WETR_LAST_ACCESS_RGN_M=\"MDYxNDAxMDE=\"; NAC=OLdABsQZqteGA; page_uid=jfNfawpzLiwssDoLlS8ssssss24-215133; NACT=1; nid_inf=1426211877; papago_skin_locale=ko; SRT30=1764406270; SRT5=1764406270; BUC=RzB0uuyqkGsQmKdpHTlI80xtxirvT3VORUdOrARznUE=",
        "Referer": "https://papago.naver.com/"
      },
      method: "GET"
    });

    console.log(`📡 API Response for "${word}": Status ${response.status}`);

    if (!response.ok) {
      console.log(`⚠️ API returned status ${response.status} for word: ${word}`);
      return null;
    }

    const data = await response.json() as PapagoResponse;
    console.log(`📦 Received data for "${word}":`, JSON.stringify(data).substring(0, 200) + '...');
    return data;
  } catch (error: any) {
    console.log(`❌ Fetch error for word "${word}": ${error.message}`);
    return null;
  }
}

async function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function translateWithPapago(text: string): Promise<string> {
  try {
    const response = await fetch('https://papago.naver.com/apis/nsmt/translate', {
      method: 'POST',
      headers: {
        "accept": "application/json",
        "accept-language": "ko",
        "authorization": "PPG ffbaf550-ce4b-4478-ae20-ee54a0e3cd60:3nITCzO9GCSWr9L0e/ZJww==",
        "cache-control": "no-cache",
        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
        "device-type": "pc",
        "pragma": "no-cache",
        "priority": "u=1, i",
        "sec-ch-ua": "\"Not_A Brand\";v=\"99\", \"Chromium\";v=\"142\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        'timestamp': Date.now().toString(),
        "x-apigw-partnerid": "papago",
        "x-ppg-ctype": "WEB_PC",
        "cookie": "NNB=ZFCDE4DECVCWQ; _ga_8P4PY65YZ2=GS2.1.s1749365250$o1$g0$t1749365250$j60$l0$h0; ba.uuid=4c6155ad-568d-4b70-bfac-a51e7da4bbcf; ASID=3b0589f40000019827bcdb750000001d; bnb_tooltip_shown_finance_v1=true; _ga=GA1.2.1705893687.1749365250; ab.storage.userId.7d7bb94a-f465-48e5-bec1-35db97daf128=g%3AZ2JG%7Ce%3Aundefined%7Cc%3A1761905082349%7Cl%3A1761905082350; ab.storage.deviceId.7d7bb94a-f465-48e5-bec1-35db97daf128=g%3A63dd0bf6-7986-8282-897c-5526a566b2ab%7Ce%3Aundefined%7Cc%3A1761905082350%7Cl%3A1761905082350; ab.storage.sessionId.7d7bb94a-f465-48e5-bec1-35db97daf128=g%3Ad2c680c5-2d3f-9d2b-c3fb-42785b70ed6b%7Ce%3A1761907197910%7Cc%3A1761905082349%7Cl%3A1761905397910; NV_WETR_LOCATION_RGN_M=\"MDYxNDAxMDE=\"; NV_WETR_LAST_ACCESS_RGN_M=\"MDYxNDAxMDE=\"; NAC=OLdABsQZqteGA; page_uid=jfNfawpzLiwssDoLlS8ssssss24-215133; NACT=1; nid_inf=1426211877; papago_skin_locale=ko; SRT30=1764406270; SRT5=1764406270; BUC=uD_D-1wRQ_qrJ2TBY9cJtxbW9ArFsXht-Uga8wXo35o=",
        "Referer": "https://papago.naver.com/"
      },
      body: new URLSearchParams({
        deviceId: 'ffbaf550-ce4b-4478-ae20-ee54a0e3cd60',
        locale: 'ko',
        dict: 'false',
        dictDisplay: '30',
        honorific: 'false',
        instant: 'true',
        paging: 'false',
        source: 'en',
        target: 'ko',
        text: text,
        usageAgreed: 'true'
      })
    });

    if (!response.ok) {
      return '';
    }

    const data = await response.json() as { translatedText: string };
    return data.translatedText || '';
  } catch (error) {
    console.log(`⚠️ Papago translation failed for: ${text.substring(0, 50)}...`);
    return '';
  }
}

async function processDictionary(subtitles: SubtitleEntry[]): Promise<void> {
  try {
    console.log('\n📚 Processing dictionary for words...');
    
    // Create dictionary directory if it doesn't exist
    if (!fs.existsSync(DICTIONARY_DIR)) {
      fs.mkdirSync(DICTIONARY_DIR, { recursive: true });
    }
    
    // Extract all unique words
    const allWords = new Set<string>();
    
    subtitles.forEach(subtitle => {
      const words = subtitle.e
        .split(/\s+/)
        .map(word => word.replace(/[,.":!?;()]/g, '').toLowerCase())
        .filter(word => word.length > 0 && /^[a-zA-Z']+$/.test(word));
      
      words.forEach(word => allWords.add(word));
    });
    
    console.log(`📖 Found ${allWords.size} unique words`);
    
    let processedCount = 0;
    let skippedCount = 0;
    let successCount = 0;
    let failedCount = 0;
    const totalWords = allWords.size;
    
    for (const word of allWords) {
      const dictionaryPath = path.join(DICTIONARY_DIR, `${word}.json`);
      
      // Skip if dictionary file already exists
      if (fs.existsSync(dictionaryPath)) {
        skippedCount++;
        if ((processedCount + skippedCount) % 50 === 0) {
          console.log(`[${processedCount + skippedCount}/${totalWords}] Progress: ${skippedCount} skipped, ${successCount} fetched, ${failedCount} failed`);
        }
        continue;
      }
      
      console.log(`[${processedCount + skippedCount + 1}/${totalWords}] Fetching: ${word}`);
      
      const dictionaryData = await fetchDictionary(word);
      
      if (dictionaryData) {
        try {
          fs.writeFileSync(dictionaryPath, JSON.stringify(dictionaryData, null, 2), 'utf-8');
          successCount++;
          console.log(`✅ Saved: ${word}.json (${dictionaryPath})`);
          
          // 파일이 실제로 생성되었는지 확인
          if (fs.existsSync(dictionaryPath)) {
            const stats = fs.statSync(dictionaryPath);
            console.log(`   📄 File size: ${stats.size} bytes`);
          } else {
            console.log(`   ⚠️ Warning: File was not created!`);
          }
        } catch (writeError: any) {
          console.log(`❌ Error writing file for "${word}": ${writeError.message}`);
          failedCount++;
        }
      } else {
        failedCount++;
        console.log(`❌ Failed to fetch: ${word}`);
        
        // Rate limiting 감지 - 연속 실패 시 더 긴 대기
        if (failedCount >= 3) {
          console.log(`⚠️ Multiple failures detected. Waiting 5 seconds...`);
          await delay(5000);
          failedCount = 0; // 카운터 리셋
        }
      }
      
      processedCount++;
      
      // Add delay to avoid rate limiting (1초로 증가)
      await delay(1000);
    }
    
    console.log(`\n✅ Dictionary processing complete!`);
    console.log(`   - Total words: ${totalWords}`);
    console.log(`   - Already existed: ${skippedCount}`);
    console.log(`   - Newly fetched: ${successCount}`);
    console.log(`   - Failed: ${failedCount}`);
    
  } catch (error: any) {
    console.error('❌ Error processing dictionary:', error.message);
  }
}

function parseVttContent(vttContent: string): Array<{ text: string; startTime: number; endTime: number }> {
  const lines = vttContent.split('\n');
  const cues: Array<{ text: string; startTime: number; endTime: number }> = [];
  
  let i = 0;
  while (i < lines.length) {
    const line = lines[i].trim();
    
    if (line.includes('-->')) {
      try {
        const [startStr, endStr] = line.split('-->').map(s => s.trim());
        const startTime = parseVttTime(startStr);
        const endTime = parseVttTime(endStr);
        
        i++;
        let text = '';
        while (i < lines.length && lines[i].trim() !== '') {
          text += lines[i].trim() + ' ';
          i++;
        }
        
        if (text.trim()) {
          cues.push({
            text: text.trim(),
            startTime,
            endTime
          });
        }
      } catch (error) {
        console.log(`⚠️ Error parsing VTT line: ${line}`);
      }
    }
    i++;
  }
  
  return cues;
}

async function copyVttFilesAndUpdateItems(videoTitle: string, subtitles: SubtitleData[]): Promise<void> {
  try {
    // VTT 디렉토리 생성
    if (!fs.existsSync(VTT_DIR)) {
      fs.mkdirSync(VTT_DIR, { recursive: true });
    }
    
    // Auto-translation 디렉토리 생성
    if (!fs.existsSync(AUTO_TRANSLATION_DIR)) {
      fs.mkdirSync(AUTO_TRANSLATION_DIR, { recursive: true });
    }

    // en-US 또는 en 파일 찾기
    const enSubtitle = subtitles.find(s => s.language === 'en-US') || subtitles.find(s => s.language === 'en');
    const koSubtitle = subtitles.find(s => s.language === 'ko');
    
    if (!enSubtitle) {
      console.log('❌ No English subtitle found');
      return;
    }
    
    // 파일명 정리
    const cleanTitle = videoTitle.replace(/[<>:"/\\|?*]/g, '_').substring(0, 100);
    
    // 영어 VTT 파일 저장 (원본 그대로)
    const enSourcePath = path.join(OUTPUT_DIR, `${cleanTitle}.${enSubtitle.language}${enSubtitle.isAutoGenerated ? '.auto' : ''}.vtt`);
    const enDestPath = path.join(VTT_DIR, `${cleanTitle}.en.vtt`);
    
    if (fs.existsSync(enSourcePath)) {
      fs.copyFileSync(enSourcePath, enDestPath);
      console.log(`✅ Copied English VTT: ${enDestPath}`);
    }
    
    // 영어 원본 JSON 저장 (auto-translation 디렉토리)
    if (enSubtitle.originalJson) {
      const enJsonPath = path.join(AUTO_TRANSLATION_DIR, `${cleanTitle}.en.json`);
      fs.writeFileSync(enJsonPath, JSON.stringify(enSubtitle.originalJson, null, 2), 'utf-8');
      console.log(`✅ Saved English original JSON: ${enJsonPath}`);
    }

    // 한국어 VTT 파일 저장 (원본 그대로)
    if (koSubtitle) {
      const koSourcePath = path.join(OUTPUT_DIR, `${cleanTitle}.${koSubtitle.language}${koSubtitle.isAutoGenerated ? '.auto' : ''}.vtt`);
      const koDestPath = path.join(VTT_DIR, `${cleanTitle}.ko.vtt`);
      
      if (fs.existsSync(koSourcePath)) {
        fs.copyFileSync(koSourcePath, koDestPath);
        console.log(`✅ Copied Korean VTT: ${koDestPath}`);
      }

      // 한국어 원본 JSON 저장 (auto-translation 디렉토리)
      if (koSubtitle.originalJson) {
        const koJsonPath = path.join(AUTO_TRANSLATION_DIR, `${cleanTitle}.ko.json`);
        fs.writeFileSync(koJsonPath, JSON.stringify(koSubtitle.originalJson, null, 2), 'utf-8');
        console.log(`✅ Saved Korean original JSON: ${koJsonPath}`);
      }
    }
    
    // items.json 업데이트
    await updateItemsJson(videoTitle);
    
    // 단어 사전 생성 (영어 VTT에서 단어 추출)
    const enCues = parseVttContent(enSubtitle.content);
    const allWords = new Set<string>();
    enCues.forEach(cue => {
      const words = cue.text.split(/\s+/)
        .map(word => word.replace(/[,.":!?;()]/g, '').toLowerCase())
        .filter(word => word.length > 0 && /^[a-zA-Z']+$/.test(word));
      words.forEach(word => allWords.add(word));
    });
    
    const subtitleEntries = Array.from(allWords).map(word => ({ e: word, k: '', t: '0s' }));
    await processDictionary(subtitleEntries as any);
    
    console.log('\n🎉 Complete! VTT files and original JSONs saved, items updated!');
    
  } catch (error: any) {
    console.error('❌ Error in copyVttFilesAndUpdateItems:', error.message);
  }
}

// 기존 convertVttToJsonAndUpdate 함수는 제거하고 새로운 함수로 대체
async function convertVttToJsonAndUpdate_OLD(videoTitle: string, subtitles: SubtitleData[]): Promise<void> {
  try {
    console.log(`\n🔍 Looking for subtitles in ${subtitles.length} captured items...`);
    subtitles.forEach(s => console.log(`  - ${s.language} (${s.content.length} chars)`));
    
    // 영어와 한국어 자막 찾기
    // en-US 우선, 없으면 en 사용
    const enSubtitle = subtitles.find(s => s.language === 'en-US') || subtitles.find(s => s.language === 'en');
    const koSubtitle = subtitles.find(s => s.language === 'ko');
    
    if (!enSubtitle) {
      console.log('❌ Missing English subtitle (tried en-US and en)');
      return;
    }
    
    console.log(`✅ Using English subtitle: ${enSubtitle.language}`);
    
    console.log('📝 Parsing VTT files...');
    const enCues = parseVttContent(enSubtitle.content);
    console.log(`✅ Parsed ${enCues.length} English cues`);
    
    if (enCues.length === 0) {
      console.log('❌ No cues found in English VTT file');
      return;
    }
    
    // Papago 번역 사용 또는 한국어 자막이 없는 경우
    if (TRANSLATION_METHOD === 'papago' || !koSubtitle) {
      if (TRANSLATION_METHOD === 'papago') {
        console.log('🌐 Using Papago translation for Korean subtitles...');
      } else {
        console.log('⚠️  Korean subtitle not found - will use Papago translation');
      }
      
      // 영어 자막을 Papago로 번역
      const matchedSubtitles: SubtitleEntry[] = [];
      let translatedCount = 0;
      
      for (let i = 0; i < enCues.length; i++) {
        const enCue = enCues[i];
        const timeInSeconds = Math.floor(enCue.startTime / 1000);
        
        console.log(`[${i + 1}/${enCues.length}] Translating: ${enCue.text.substring(0, 50)}...`);
        
        const koText = await translateWithPapago(enCue.text);
        if (koText) {
          translatedCount++;
        }
        
        matchedSubtitles.push({
          t: `${timeInSeconds}s`,
          e: enCue.text,
          k: koText
        });
        
        // Rate limiting: 500ms delay between requests
        if (i < enCues.length - 1) {
          await delay(500);
        }
      }
      
      console.log(`✅ Translated ${translatedCount} out of ${enCues.length} subtitles`);
      
      // JSON 파일 저장
      if (!fs.existsSync(SCRIPTS_DIR)) {
        fs.mkdirSync(SCRIPTS_DIR, { recursive: true });
      }
      
      const jsonFilePath = path.join(SCRIPTS_DIR, `${videoTitle}.json`);
      fs.writeFileSync(jsonFilePath, JSON.stringify(matchedSubtitles, null, 2), 'utf8');
      console.log(`✅ Saved JSON: ${jsonFilePath}`);
      
      // items.json 업데이트
      await updateItemsJson(videoTitle);
      
      // 단어 사전 생성
      await processDictionary(matchedSubtitles);
      
      console.log('\n🎉 Complete! (Translated with Papago)');
      return;
    }
    
    console.log('✅ Found both English and Korean subtitles');
    console.log('📝 Parsing Korean VTT file...');
    
    const koCues = parseVttContent(koSubtitle.content);
    console.log(`✅ Parsed ${koCues.length} Korean cues`);
    
    if (koCues.length === 0) {
      console.log('❌ No cues found in Korean VTT file');
      return;
    }
    
    // 시간 기반으로 자막 매칭 (영어 시간 범위 내의 모든 한국어 자막 합치기)
    const matchedSubtitles: SubtitleEntry[] = [];
    
    for (const enCue of enCues) {
      // 영어 자막의 시간 범위 내에 있는 모든 한국어 자막 찾기
      const overlappingKoCues = koCues.filter(koCue => {
        const overlap = Math.min(enCue.endTime, koCue.endTime) - Math.max(enCue.startTime, koCue.startTime);
        return overlap > 0;
      });
      
      // 시작 시간 순으로 정렬
      overlappingKoCues.sort((a, b) => a.startTime - b.startTime);
      
      // 모든 한국어 자막을 / 로 구분하여 연결
      const koText = overlappingKoCues.map(koCue => koCue.text).join(' / ');
      
      // 시간을 초 단위 문자열로 변환 (예: "0s", "6s")
      const timeInSeconds = Math.floor(enCue.startTime / 1000);
      
      matchedSubtitles.push({
        t: `${timeInSeconds}s`,
        e: enCue.text,
        k: koText
      });
    }
    
    console.log(`✅ Matched ${matchedSubtitles.filter(s => s.k).length} out of ${matchedSubtitles.length} English subtitles with Korean`);
    
    console.log(`✅ Matched ${matchedSubtitles.length} subtitle pairs`);
    
    // JSON 파일 저장
    if (!fs.existsSync(SCRIPTS_DIR)) {
      fs.mkdirSync(SCRIPTS_DIR, { recursive: true });
    }
    
    const jsonFilePath = path.join(SCRIPTS_DIR, `${videoTitle}.json`);
    fs.writeFileSync(jsonFilePath, JSON.stringify(matchedSubtitles, null, 2), 'utf8');
    console.log(`✅ Saved JSON: ${jsonFilePath}`);
    
    // items.json 업데이트
    let items: VideoItem[] = [];
    if (fs.existsSync(ITEMS_JSON_PATH)) {
      const itemsContent = fs.readFileSync(ITEMS_JSON_PATH, 'utf8');
      items = JSON.parse(itemsContent);
      console.log(`📖 Read existing items.json with ${items.length} items`);
    } else {
      console.log(`⚠️ items.json not found at: ${ITEMS_JSON_PATH}`);
    }
    
    // 이미 존재하는지 확인 (link로 비교)
    const youtubeLink = `https://www.youtube.com/watch?v=${YOUTUBE_VIDEO_ID}`;
    const existingIndex = items.findIndex(item => item.link === youtubeLink);
    
    const newItem: VideoItem = {
      name: videoTitle,
      type: 'youtube',
      img: `https://img.youtube.com/vi/${YOUTUBE_VIDEO_ID}/0.jpg`,
      link: youtubeLink
    };
    
    if (existingIndex >= 0) {
      items[existingIndex] = newItem;
      console.log(`✅ Updated existing item in items.json`);
    } else {
      items.push(newItem);
      console.log(`✅ Added new item to items.json`);
    }
    
    fs.writeFileSync(ITEMS_JSON_PATH, JSON.stringify(items, null, 2), 'utf8');
    console.log(`✅ Saved items.json: ${ITEMS_JSON_PATH}`);
    
    // 단어 사전 생성
    await processDictionary(matchedSubtitles);
    
    console.log('\n🎉 Complete! All files generated and updated successfully!');
  } catch (error: any) {
    console.error('❌ Error in convertVttToJsonAndUpdate:', error.message);
  }
}

async function updateItemsJson(videoTitle: string): Promise<void> {
  try {
    // items.json 업데이트
    let items: VideoItem[] = [];
    if (fs.existsSync(ITEMS_JSON_PATH)) {
      const itemsContent = fs.readFileSync(ITEMS_JSON_PATH, 'utf8');
      items = JSON.parse(itemsContent);
      console.log(`📖 Read existing items.json with ${items.length} items`);
    } else {
      console.log(`⚠️ items.json not found at: ${ITEMS_JSON_PATH}`);
    }

    // 이미 존재하는지 확인 (link로 비교)
    const youtubeLink = `https://www.youtube.com/watch?v=${YOUTUBE_VIDEO_ID}`;
    const existingIndex = items.findIndex(item => item.link === youtubeLink);

    // VTT 파일명과 동일하게 특수문자 제거
    const cleanTitle = videoTitle.replace(/[<>:"/\\|?*]/g, '_').substring(0, 100);

    const newItem: VideoItem = {
      name: cleanTitle,  // 파일명과 동일하게 정리된 제목 사용
      type: 'youtube',
      img: `https://img.youtube.com/vi/${YOUTUBE_VIDEO_ID}/0.jpg`,
      link: youtubeLink
    };

    if (existingIndex >= 0) {
      items[existingIndex] = newItem;
      console.log(`✅ Updated existing item in items.json`);
    } else {
      items.push(newItem);
      console.log(`✅ Added new item to items.json`);
    }

    fs.writeFileSync(ITEMS_JSON_PATH, JSON.stringify(items, null, 2), 'utf8');
    console.log(`✅ Saved items.json: ${ITEMS_JSON_PATH}`);

  } catch (error: any) {
    console.error('❌ Error in convertVttToJsonAndUpdate:', error.message);
  }
}

async function saveSubtitle(subtitleData: SubtitleData, videoTitle: string): Promise<void> {
  try {
    if (!fs.existsSync(OUTPUT_DIR)) {
      fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    const cleanTitle = videoTitle.replace(/[<>:"/\\|?*]/g, '_').substring(0, 100);
    const autoSuffix = subtitleData.isAutoGenerated ? '.auto' : '';
    const filename = `${cleanTitle}.${subtitleData.language}${autoSuffix}.vtt`;
    const filepath = path.join(OUTPUT_DIR, filename);

    fs.writeFileSync(filepath, subtitleData.content, 'utf8');
    
    console.log(`✅ Saved: ${filename}`);
    console.log(`📁 Path: ${filepath}`);
    
  } catch (error: any) {
    console.error(`❌ Error saving ${subtitleData.language} subtitle:`, error.message);
  }
}

async function downloadYouTubeSubtitles() {
  console.log(`🎥 YouTube Video ID: ${YOUTUBE_VIDEO_ID}`);
  console.log(`🔗 YouTube URL: ${YOUTUBE_URL}`);
  console.log(`📁 Output Directory: ${OUTPUT_DIR}`);
  console.log('');

  console.log('🚀 Launching browser...');
  const browser = await chromium.launch({ 
    headless: false,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-blink-features=AutomationControlled',
      '--disable-dev-shm-usage',
      '--disable-web-security'
    ],
    slowMo: 300
  });
  
  const context = await browser.newContext({
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    viewport: { width: 1920, height: 1080 },
    locale: 'ko-KR',
    timezoneId: 'Asia/Seoul',
    permissions: ['geolocation']
  });
  
  await context.addInitScript(() => {
    Object.defineProperty(navigator, 'webdriver', {
      get: () => undefined
    });
    
    (window as any).chrome = {
      runtime: {}
    };
    
    const originalQuery = window.navigator.permissions.query;
    window.navigator.permissions.query = (parameters: any) => (
      parameters.name === 'notifications' ?
        Promise.resolve({ state: 'denied' } as PermissionStatus) :
        originalQuery(parameters)
    );
  });
  
  const page = await context.newPage();
  const capturedSubtitles: SubtitleData[] = [];
  const client = await context.newCDPSession(page);
  await client.send('Network.enable');
  
  // 자막 캡처 활성화 플래그
  let captureEnabled = false;

  // 요청 ID를 추적하기 위한 Map
  const pendingRequests = new Map<string, { url: string; language: string; isAutoGenerated: boolean }>();

  client.on('Network.responseReceived', (params: any) => {
    const url = params.response.url;
    
    if (url.includes('timedtext') && !url.includes('.js')) {
      // 캡처가 활성화되지 않았으면 무시
      if (!captureEnabled) {
        console.log(`⏭️ Skipping timedtext (capture not enabled yet): ${url.substring(0, 100)}...`);
        return;
      }

      console.log(`📡 Network response received: ${url.substring(0, 150)}...`);
      console.log(`📊 RequestId: ${params.requestId}, Status: ${params.response.status}, MIME: ${params.response.mimeType}`);
      
      const langMatch = url.match(/[&?]lang=([^&]+)/);
      const tlangMatch = url.match(/[&?]tlang=([^&]+)/);
      
      let language = tlangMatch?.[1] || langMatch?.[1] || 'unknown';
      language = decodeURIComponent(language);
      
      const isAutoGenerated = url.includes('kind=asr');
      
      // 요청 정보 저장
      pendingRequests.set(params.requestId, { url, language, isAutoGenerated });
      console.log(`📝 Stored request info for ${language} (RequestId: ${params.requestId})`);
    }
  });

  client.on('Network.loadingFinished', async (params: any) => {
    const requestInfo = pendingRequests.get(params.requestId);
    
    if (!requestInfo) {
      return;
    }

    console.log(`✅ Loading finished for ${requestInfo.language} (RequestId: ${params.requestId})`);
    
    try {
      console.log(`🔄 Attempting to get response body for ${requestInfo.language}...`);
      
      const responseBody = await client.send('Network.getResponseBody', {
        requestId: params.requestId
      });
      
      let content = '';
      if (responseBody.base64Encoded) {
        content = Buffer.from(responseBody.body, 'base64').toString('utf-8');
        console.log(`📦 Decoded base64 content: ${content.length} bytes`);
      } else {
        content = responseBody.body;
        console.log(`📦 Got text content: ${content.length} bytes`);
      }
      
      let processedContent = content;
      let originalJson: any = null;

      if (requestInfo.url.includes('fmt=json3') && content.trim().startsWith('{')) {
        try {
          const jsonData = JSON.parse(content);
          originalJson = jsonData;
          processedContent = convertJson3ToVtt(jsonData);
          console.log(`🔄 Converted JSON3 to VTT for ${requestInfo.language}`);
        } catch (parseError) {
          console.log(`⚠️ Failed to parse JSON3: ${parseError}`);
        }
      }
      
      if (processedContent && processedContent.trim().length > 10) {
        capturedSubtitles.push({
          language: requestInfo.language,
          content: processedContent,
          isAutoGenerated: requestInfo.isAutoGenerated,
          url: requestInfo.url,
          originalJson
        });
        console.log(`💾 Stored subtitle data for ${requestInfo.language} (${processedContent.length} chars)`);
      } else {
        console.log(`⚠️ Content too short for ${requestInfo.language}: ${processedContent.length} chars`);
      }
      
      // 처리 완료된 요청 제거
      pendingRequests.delete(params.requestId);
      
    } catch (error: any) {
      console.log(`❌ Error getting response body for ${requestInfo.language}: ${error.message}`);
      console.log(`   RequestId: ${params.requestId}`);
      console.log(`   URL: ${requestInfo.url.substring(0, 150)}...`);
      pendingRequests.delete(params.requestId);
    }
  });

  try {
    console.log('🌐 Navigating to YouTube page...');
    await page.goto(YOUTUBE_URL, { waitUntil: 'networkidle' });
    
    console.log('⏳ Waiting for page to fully load...');
    await page.waitForTimeout(3000);
    
    // 광고 스킵 처리
    console.log('📺 Checking for ads...');
    try {
      // 광고가 있는지 확인 (최대 5초 대기)
      const adExists = await page.locator('.video-ads').isVisible({ timeout: 5000 }).catch(() => false);
      
      if (adExists) {
        console.log('⏭️  Ad detected, waiting for skip button...');
        
        // 스킵 버튼이 나타날 때까지 대기 (최대 10초)
        const skipButton = page.locator('button.ytp-ad-skip-button, button.ytp-skip-ad-button, .ytp-ad-skip-button-modern');
        await skipButton.waitFor({ state: 'visible', timeout: 10000 }).catch(() => {
          console.log('⚠️ Skip button not found, continuing anyway...');
        });
        
        // 스킵 버튼 클릭
        if (await skipButton.isVisible().catch(() => false)) {
          await skipButton.click();
          console.log('✅ Ad skipped!');
          await page.waitForTimeout(1000);
        }
      } else {
        console.log('✅ No ads detected');
      }
    } catch (error) {
      console.log('⚠️ Ad handling error (continuing anyway):', error);
    }
    
    const videoTitle = await page.evaluate(() => {
      const titleSelectors = [
        'h1.ytd-video-primary-info-renderer',
        'meta[property="og:title"]',
        'title'
      ];
      
      for (const selector of titleSelectors) {
        const element = document.querySelector(selector);
        if (element) {
          if (element.tagName === 'META') {
            return (element as any).content;
          } else if (element.tagName === 'TITLE') {
            return element.textContent?.replace(' - YouTube', '') || '';
          } else {
            return element.textContent || '';
          }
        }
      }
      
      return `YouTube_Video_${(window as any).location.search.match(/v=([^&]+)/)?.[1] || 'unknown'}`;
    });
    
    console.log(`🎬 Video Title: ${videoTitle}`);
    
    // 자막 캡처 활성화 (이제부터 timedtext 요청을 캡처함)
    console.log('✅ Enabling subtitle capture...');
    captureEnabled = true;

    // 0. 자막 초기화 - "사용 안함"으로 설정
    console.log('🔧 Opening settings to disable subtitles first...');
    await page.click('button.ytp-settings-button', { timeout: 5000 });
    await page.waitForTimeout(1000);
    
    console.log('📝 Opening subtitles menu...');
    await page.locator('text=자막').click({ timeout: 5000 });
    await page.waitForTimeout(1500);
    
    console.log('❌ Setting subtitles to "사용 안함"...');
    try {
      await page.locator('[role="menuitemradio"]').filter({ hasText: '사용 안함' }).first().click({ timeout: 3000 });
      console.log('✅ Subtitles disabled');
    } catch {
      try {
        await page.locator('[role="menuitemradio"]').filter({ hasText: 'Off' }).first().click({ timeout: 3000 });
        console.log('✅ Subtitles turned off');
      } catch {
        console.log('⚠️ Could not find disable option, continuing anyway...');
      }
    }
    await page.waitForTimeout(1000);
    await page.keyboard.press('Escape');
    await page.waitForTimeout(500);

    // 1. 영어 자막 가져오기
    console.log('🔧 Clicking settings button for English subtitles...');
    await page.click('button.ytp-settings-button', { timeout: 5000 });
    await page.waitForTimeout(1000);
    
    console.log('📝 Clicking subtitles menu...');
    await page.locator('text=자막').click({ timeout: 5000 });
    await page.waitForTimeout(1500);
    
    console.log('🇺🇸 Selecting English subtitles...');
    // 영어 자막 선택 시도 (원본 우선, 자동 생성은 나중에)
    let englishSelected = false;
    
    // 1순위: 원본 영어 자막들
    const originalEnglishOptions = [
      /^영어$/,
      /^영어\(미국\)$/,
      /^영어\(미국\) - Captions$/,
      /^English$/,
      /^English \(United States\)$/,
      /^English \(US\)$/
    ];
    
    for (const pattern of originalEnglishOptions) {
      try {
        await page.locator('[role="menuitemradio"]').filter({ hasText: pattern }).first().click({ timeout: 2000 });
        console.log(`✅ Selected: ${pattern.source} (original)`);
        englishSelected = true;
        break;
      } catch {
        continue;
      }
    }
    
    // 2순위: 자동 생성 영어 자막들
    if (!englishSelected) {
      const autoGeneratedOptions = [
        '영어 (자동 생성됨)',
        '영어(미국) (자동 생성됨)',
        'English (auto-generated)',
        'English (United States) (auto-generated)'
      ];
      
      for (const option of autoGeneratedOptions) {
        try {
          await page.locator('[role="menuitemradio"]').filter({ hasText: option }).first().click({ timeout: 2000 });
          console.log(`✅ Selected: ${option}`);
          englishSelected = true;
          break;
        } catch {
          continue;
        }
      }
    }
    
    // 3순위: 자동 번역으로 영어 선택
    if (!englishSelected) {
      console.log('⚠️ No direct English subtitle found, trying auto-translate...');
      const autoTranslateExists = await page.locator('text=자동 번역').isVisible({ timeout: 2000 }).catch(() => false);
      
      if (autoTranslateExists) {
        console.log('✅ Found auto-translate menu');
        await page.locator('text=자동 번역').click({ timeout: 5000 });
        await page.waitForTimeout(1500);
        
        console.log('🇺🇸 Selecting English from auto-translate...');
        try {
          await page.locator('[role="menuitemradio"]:has-text("영어")').first().click({ timeout: 5000 });
          console.log('✅ Selected: 영어 (auto-translate)');
          englishSelected = true;
        } catch {
          await page.locator('[role="menuitemradio"]:has-text("English")').first().click({ timeout: 5000 });
          console.log('✅ Selected: English (auto-translate)');
          englishSelected = true;
        }
      }
    }
    
    if (!englishSelected) {
      throw new Error('❌ Could not find any English subtitle option');
    }
    
    console.log('📡 Waiting for English subtitle data...');
    await page.waitForTimeout(3000);
    
    // 2. 한국어 자막 가져오기 (자동번역 → 한국어)
    console.log('🔙 Going back to subtitle menu...');
    await page.keyboard.press('Escape');
    await page.waitForTimeout(500);
    
    console.log('🔧 Reopening settings menu...');
    await page.click('button.ytp-settings-button', { timeout: 5000 });
    await page.waitForTimeout(1000);
    
    console.log('📝 Clicking subtitles menu...');
    await page.locator('text=자막').click({ timeout: 5000 });
    await page.waitForTimeout(1500);
    
    console.log('🌐 Looking for Korean subtitle options...');
    
    // 1순위: 직접 한국어 자막이 있는지 확인
    const koreanSubtitleExists = await page.locator('[role="menuitemradio"]').filter({ hasText: /^한국어$/ }).isVisible({ timeout: 2000 }).catch(() => false);
    
    if (koreanSubtitleExists) {
      console.log('✅ Found direct Korean subtitle');
      await page.locator('[role="menuitemradio"]').filter({ hasText: /^한국어$/ }).first().click({ timeout: 3000 });
      console.log('✅ Selected: 한국어');
    } else {
      console.log('⚠️ Direct Korean subtitle not found, checking auto-translate...');
      
      // 2순위: 자동 번역 메뉴 확인
      const autoTranslateExists = await page.locator('text=자동 번역').isVisible({ timeout: 2000 }).catch(() => false);
      
      if (autoTranslateExists) {
        console.log('✅ Found auto-translate menu');
        await page.locator('text=자동 번역').click({ timeout: 5000 });
        await page.waitForTimeout(1500);
        
        console.log('🇰🇷 Selecting Korean language from auto-translate...');
        await page.locator('[role="menuitemradio"]:has-text("한국어")').first().click({ timeout: 5000 });
        console.log('✅ Selected: 한국어 (auto-translate)');
      } else {
        console.log('⚠️ Auto-translate not found, looking for 영어(미국)...');
        
        // 3순위: 영어(미국) 찾아서 클릭
        try {
          await page.locator('[role="menuitemradio"]').filter({ hasText: '영어(미국)' }).first().click({ timeout: 3000 });
          console.log('✅ Selected: 영어(미국)');
        } catch {
          console.log('⚠️ 영어(미국) not found, trying English (United States)...');
          await page.locator('[role="menuitemradio"]').filter({ hasText: 'English (United States)' }).first().click({ timeout: 3000 });
          console.log('✅ Selected: English (United States)');
        }
      }
    }
    
    console.log('📡 Waiting for Korean subtitle data...');
    await page.waitForTimeout(5000);
    
    await page.keyboard.press('Escape');
    
    console.log('⏳ Final wait for all network requests...');
    await page.waitForTimeout(3000);
    
    console.log(`\n📊 Captured ${capturedSubtitles.length} subtitle(s)`);
    
    if (capturedSubtitles.length > 0) {
      // 1. VTT 파일 저장
      for (const subtitle of capturedSubtitles) {
        console.log(`\n💾 Processing ${subtitle.language} subtitle...`);
        await saveSubtitle(subtitle, videoTitle);
      }
      
      console.log('\n✅ All VTT files saved successfully!');
      console.log(`📂 VTT files location: ${OUTPUT_DIR}`);
      
      // 2. VTT 파일 복사 및 items.json 업데이트
      console.log('\n📋 Copying VTT files and updating items.json...');
      await copyVttFilesAndUpdateItems(videoTitle, capturedSubtitles);
      
    } else {
      console.log('❌ No subtitles were captured');
    }

  } catch (error: any) {
    console.error('❌ Error:', error.message);
  } finally {
    await browser.close();
  }
}

console.log('🎬 YouTube Subtitle Downloader (Network Interception)');
console.log('===================================================');
downloadYouTubeSubtitles();
